# Generated by Django 4.2.1 on 2023-05-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_remove_transction_balance_after_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transction',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transction',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
