# Generated by Django 4.2.1 on 2023-05-26 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_app', '0008_bankaccounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccounts',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bankaccounts',
            name='name_of_accountholder',
        ),
        migrations.AddField(
            model_name='bankaccounts',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankaccounts',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to=settings.AUTH_USER_MODEL),
        ),
    ]
