# Generated by Django 4.2.1 on 2023-05-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_remove_bankaccounts_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccounts',
            old_name='alias',
            new_name='nickname',
        ),
    ]
